### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by tmayoff** [mdgaziur/findex#6] opened 2021-11-07 01:57 UTC
When I try to run it I just get this crash

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/query.rs:148:41
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

And if this is of any help with `RUST_BACKTRACE=full`
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/query.rs:148:41
stack backtrace:
   0:     0x564cc34c616d - <unknown>
   1:     0x564cc344949c - <unknown>
   2:     0x564cc34c57d4 - <unknown>
   3:     0x564cc34c5613 - <unknown>
   4:     0x564cc34e4a56 - <unknown>
   5:     0x564cc34e49f6 - <unknown>
   6:     0x564cc34e49b2 - <unknown>
   7:     0x564cc3423530 - <unknown>
   8:     0x564cc342368c - <unknown>
   9:     0x564cc3460451 - <unknown>
  10:     0x564cc345d0d6 - <unknown>
  11:     0x564cc342b3f7 - <unknown>
  12:     0x564cc343148e - <unknown>
  13:     0x7f1dec3add8f - g_closure_invoke
  14:     0x7f1dec3c9718 - <unknown>
  15:     0x7f1dec3cadd9 - g_signal_emit_valist
  16:     0x7f1dec3cb330 - g_signal_emit
  17:     0x7f1deb843739 - <unknown>
  18:     0x7f1deb84e28a - g_application_run
  19:     0x564cc3434990 - <unknown>
  20:     0x564cc3431263 - <unknown>
  21:     0x564cc34336bd - <unknown>
  22:     0x7f1deb457b25 - __libc_start_main
  23:     0x564cc342805e - <unknown>
  24:                0x0 - <unknown>
```

**Comment by tmayoff** [comment] 2021-11-07 01:58
I actually think this is the same issue as #5

**Comment by murlakatamenka** [comment] 2021-11-07 09:44
@tmayoff this is different issue from #5, it occurs when desktop entry has no `Name` section.

Needs to be handled separately.

**Comment by mdgaziur** [comment] 2021-11-07 13:35
Well, I guess the finder should ignore desktop files when they have no "Name". What do you think? 🤔

**Comment by murlakatamenka** [comment] 2021-11-07 14:01
I think it's better to show some default label like  "⚠️ Nameless Application :warning:" (:smiley:) or "-----" with its `Exec` line. You'll still allow to launch it but will show that desktop entry can be improved.

**Comment by mdgaziur** [comment] 2021-11-07 14:10
So, findex should match query with command?

**Comment by murlakatamenka** [comment] 2021-11-07 14:13
Oh, right, you need to filter apps by name first :facepalm: 

Well, skip such entries than, they're broken, right?

**Comment by mdgaziur** [comment] 2021-11-07 14:22
Yeah IG. It's a required entry.

Check this: https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

**Comment by tmayoff** [comment] 2021-11-07 16:42
I debugged the program to find out which application was causing it and it's Gnome's Software center

![image](https://user-images.githubusercontent.com/10094264/140653806-7b3cf211-9e49-45e0-afdd-ae75b821c177.png)

**Comment by yochananmarqos** [comment] 2021-11-07 20:19
Still seeing the same error with the latest commit, but the line number changed: `src/query.rs:146:41`.

**Comment by tmayoff** [comment] 2021-11-07 20:31
I don't think the change has been merged it's still open on the pull request. The last commit was for something else it seems

I manually applied the same change from the PR and it works for me at least

**Comment by yochananmarqos** [comment] 2021-11-07 21:30
Ah, I missed the PR. Thanks.

**Comment by mdgaziur** [comment] 2021-11-08 03:02
I have merged the PR. Closing the issue. Please tell if the issue is still there

**Closed by mdgaziur** 2021-11-08 03:02 UTC
Labels: bug
